name: Actions

on: [push, pull_request]

jobs:
  run-actions:
    runs-on: ubuntu-latest
    steps:
      - name: List files
        run: |
          pwd
          ls -a
      - name: Checkout
        uses: actions/checkout@v1
      - name: List files after Checkout
        run: |
          pwd
          ls -a
      - name: JS Action
        uses: actions/hello-world-javascript-action@v1
        id: greet
        with:
          who-to-greet: Leo
      - name: Log  gretting time
        run: echo "${{steps.greet.outputs.time}}""
